apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: learning-bots
spec:
  selector:
    app: learning-bots-api
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
