apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-bots-config
  namespace: learning-bots
data:
  REDIS_HOST: "redis-master.minecraft-ai.svc.cluster.local"
  REDIS_PORT: "6379"
  MONGO_HOST: "mongodb.minecraft-ai.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "mindcraft"
  QDRANT_HOST: "qdrant.minecraft-ai.svc.cluster.local"
  QDRANT_PORT: "6333"
  CORS_ORIGIN: "*"
