apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: learning-bots
spec:
  selector:
    app: learning-bots-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30300
      protocol: TCP
  type: NodePort
